import Head from 'next/head';
import Image from 'next/legacy/image';
import { FunctionComponent, PropsWithChildren } from 'react';
import { Footer, Header, Navbar } from '@components/common';

const BaseLayout: FunctionComponent<PropsWithChildren> = ({ children }) => {
  return (
    <>
      <div className='mx-auto max-w-7xl space-y-8 px-4 sm:px-6 lg:px-8'>
        <Head>
          <title>Dmitry Sevryukov - porfolio</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>

        <div className='relative'>
          <div className='relative z-10 bg-white pb-8 sm:pb-16 md:pb-20 lg:w-full lg:max-w-2xl lg:pb-28 xl:pb-32'>
            <Navbar />
            <Header />
          </div>
          <div className='relative lg:absolute lg:inset-y-0 lg:right-0 lg:w-1/2'>
            <Image
              priority
              layout='fill'
              alt=''
              className='h-56 w-full object-cover sm:h-72 md:h-96 lg:h-full lg:w-full'
              src='/IMG_5530.JPG'
            />
          </div>
        </div>

        <div className='mx-auto max-w-2xl px-4 py-16 sm:px-6 sm:py-24 lg:max-w-7xl lg:px-8'>
          {children}
        </div>
      </div>
      <Footer />
    </>
  );
};

export default BaseLayout;
